graph LR
    BEGIN -- "(" --> COMMENT -- ")" --> END
    COMMENT -- "[^)]*" --> COMMENT
    %% any number of non-) characters

    %% Numbers
    BEGIN -- "[0-9]" --> DIGIT
    BEGIN -- "{" --> MULTIDIGIT
    DIGIT --> NUMBER
    MULTIDIGIT -- "[0-9]+" --> MULTIDIGIT
    FLOAT -- "[0-9]*" --> FLOAT
    MULTIDIGIT -- "." --> MULTIFLOAT
    MULTIDIGIT -- "}" --> NUMBER
    MULTIDIGIT -- "else" --> ERR
    MULTIFLOAT -- "else" --> ERR
    MULTIFLOAT -- "[0-9]" --> FLOAT
    FLOAT -- "}" --> NUMBER
    FLOAT -- "else" --> ERR
    NUMBER --> END

    %% Strings
    BEGIN -- "double quote" --> STRING
    STRING -- "not double quote" --> STRING
    STRING -- "double quote" --> END

    %% Lists
    BEGIN -- "[" --> LISTBEGIN
    BEGIN -- "]" --> LISTEND
    BEGIN -- "." --> LISTSEP
    LISTBEGIN & LISTEND & LISTSEP --> END

    %% Functions
    BEGIN -- "<" --> FUNNAME
    FUNNAME -- "Not whitespace" --> FUNNAME
    FUNNAME -- ">" --> END
    BEGIN -- "/" --> FUNDEF
    FUNDEF -- "else" --> FUNDEF
    FUNDEF -- "\" --> END

    %% Label Definition
    BEGIN -- "⟨" --> LABEL
    LABEL -- "[^⟩]" --> LABEL
    LABEL -- "⟩" --> END

    %% Everything else
    BEGIN -- "else" --> COMMAND --> END